Repository platform9/express-cli, pull requests merged in 2019-11, with the labels that each got.

#25 Fix the DNS resolver variables
  pf9/config/commands.py
  pf9/modules/util.py
  tests/test_cli.py
Labels: bug

#26 Drop PMO specific parameters from config create command
  pf9/__init__.pyc
  pf9/config/commands.py
  tests/__pycache__/test_cli.cpython-27-PYTEST.pyc
  tests/test_cli.py
Labels: enhancement

#28 Initial cut of the CLI setup script
  cli-setup.sh
Labels: enhancement

#29 PMK prep-node implementation
  pf9/cluster/commands.py
  pf9/express.py
  pf9/templates/pmk_inventory.tpl
Labels: enhancement

#31 Pmkft/add cluster commands
  pf9/cluster/cluster-attach.py
  pf9/cluster/cluster_create.py
  pf9/cluster/commands.py
  pf9/config/commands.py
  pf9/modules/ostoken.py
  pf9/modules/util.py
Labels: enhancement

#32 Implement cluster attach and bootstrap commands
  cli-setup.sh
  pf9/cluster/cluster-attach.py
  pf9/cluster/cluster_attach.py
  pf9/cluster/cluster_create.py
  pf9/cluster/commands.py
  pf9/modules/ostoken.py
  pf9/modules/util.py
  setup.py
Labels: enhancement

#36 Address initial set of CLI issues
  cli-setup.sh
  pf9/cluster/commands.py
Labels: bug

#37 Incremental version of CLI fit and finish
  cli-setup.sh
  pf9/cluster/cluster_attach.py
  pf9/cluster/cluster_create.py
  pf9/cluster/commands.py
  pf9/cluster/helpers.py
  pf9/exceptions.py
  pf9/modules/ostoken.py
  setup.py
Labels: enhancement

#42 Handle certain error conditions with cli-setup.sh
  cli-setup.sh
Labels: bug

#46 Usability enhancements
  pf9/cluster/commands.py
  pf9/config/commands.py
  tests/test_cli.py
Labels: bug, enhancement

#47 No more garbage output from cli-setup.sh
  cli-setup.sh
Labels: enhancement

#48 Pass custom python env to get access to venv modules + Expose ansible...
  pf9/cluster/commands.py
Labels: enhancement
